### ISSUE TITLE
How to link Low level Requirements with High level Requirements IDs ?

### ISSUE THREAD

**Issue by hamsa-g** [GEN-AUG/SDLC_01_Falcon#4]

**Comment by Sampanna-T** [comment]
why would there be any need to link low level requirements to the high level requirements? As far as what I know high level requirements gives overall picture of the project whereas low level requirements splits the overall project into smaller parts ... to complete picture of smaller sections

**Comment by Sampanna-T** [comment]
why would there be any need to link low level requirements to the high level requirements? As far as what I know high level requirements gives overall picture of the project whereas low level requirements splits the overall project into smaller parts ... to give complete picture of smaller sections

**Comment by Sampanna-T** [comment]
I think you were right about the linking part. My bad @259149

**Comment by KAUSI110799** [comment]
A high level requirement is  further divided into many low level requirements. A project may contain many high level requirements accordingly many low level requirements as well. Since every  high level requirements is given a unique ID, Each and every low level requirement would be a part of  a particular high level requirement .so we need to link a low level requirement with its respective high level requirement ID.

Hope this answered your question
